[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]

[phases.install]
cmds = [
  "cd server && pip install -r requirements.txt"
]

[start]
cmd = "cd server && uvicorn main:app --host 0.0.0.0 --port $PORT"

